name: planb.moscow
favicon: null
layout_spectrum: 0.51536
typography_spectrum: 0.6462604489643127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2c2e2b'
    - '#666256'
    - '#888983'
    - '#a9aeaa'
  brandStrength: 0.5
  lightness: 0.8861153761390597
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
